name: Build and push image
on:
  push:
  workflow_dispatch:
env:  
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Display ls
      run: ls ./app
    - name: Build and push image
      uses: ./.github/actions/build-and-push-images
      id: build
      with:
        registry: ${{ env.REGISTRY }}
        context: ./app
        path: ./app/Dockerfile
        image-tag: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        registry-username: ${{ github.actor }}
        registry-password: ${{ secrets.GH_TOKEN }}
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Test
      run: |
        docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GH_TOKEN }}
        docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} -v .:/app pytest main.py

